server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: "/api/v1.0"
  max-http-header-size: 80KB
logging:
  config: classpath:log4j2.xml
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bwton?serverTimezone=GMT%2B8
    username: bwton
    password: 123456
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikarliCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: 0.0.0.0
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: pers.jiangyinzuo.carbon.dao.mapper
