server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: "/api/v1.0"
  max-http-header-size: 80KB
logging:
  config: classpath:log4j2.xml
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
